### ISSUE TITLE
Comments SK 1

### ISSUE THREAD

**Issue by skeydan** [muschellij2/flexconn#1]
The package is looking great, with the abstractions & possibility to work 2d as well as 3d...!

Few things I suggest we add (in no special order)

- ```get_model``` as  a higher level abstraction, so flexconn_conv_chain is internal

- a train-test split like I've added in the original repo now

- like you said in the mail, a functionality for generate the predicted class probs & classes for test data (now looking in test.py finally mapped the "memberships" and "masks" to familiar terminology ;-)) 

- when we have that, we can also calculate accuracy on the original mask (mean squared error is not so helpful for evaluation even though it's fine for training)

- let the user choose the threshold

- let the user choose the batchsize (anything but 1 is killing me :-(()

**Comment by muschellij2** [comment]
I think having `flexconn_conv_chain` as exported doesn't really hurt, but what additional abstractions were you seeing for `flexconn_model`?

**Comment by skeydan** [comment]
I meant having the whole model encapsulated in a function, like they do in Python

```
model <- get_model()
```

I normally don't do it when developing a model / writing a blog post but for a package this would be different I guess...

**Comment by muschellij2** [comment]
So we have that: `res = flexconn_model()`

**Comment by skeydan** [comment]
cool!

**Comment by skeydan** [comment]
Hi John :-)

... saw you added a predict function that works on patches (not whole images)... do you think this is the way to go? You know best what users will expect...
Is there anything I can help with now? 
(Like e.g. test the model? If so, do you think I can completely switch to the package for that? That would seem safest to me, so I test with the exact same data that later will come with the package)?
Also, I guess we still need an "entry point" for users, I don't know what you're having in mind for that?

**Comment by muschellij2** [comment]
I have added `patches_to_volume` https://github.com/muschellij2/flexconn/blob/master/R/patches_to_volume.R so that the prediction can give you an image back versus the patch predictions.

**Comment by muschellij2** [comment]
Right now, have prediction abilities to get a probability map out, so I'm going to close and make new issues with train/test split and thresholding issues.
