### ISSUE TITLE
model testing and predictions

### ISSUE THREAD

**Issue by skeydan** [muschellij2/flexconn#7]
I've added a model resulting from training for 5 epochs (actually the 4th epoch was best, but this is just a test), on 21 atlases.
(Added this to github so you can quickly check for yourself, we can later remove it).

Then testing on the example atlases that come with flexconn, I can get model predictions on the pre-processed data directly from keras, but when I call ```flexconn_predict``` or ```flexconn_predict_with_patches``` my machine gets out of memory at over 41 G used...
First I thought this must come from ```get_volume_from_patches``` but that isn't even called in ```flexconn_predict_with_patches```...

Regarding predictions, I think all functions do this via patches, right? What do you think about additionally predicting on the whole image (see problem of boundary handling from email discussions with Roy)? (Just asking, not suggesting - I'm totally not the expert here!)

**Comment by muschellij2** [comment]
This should already be in there with `flexconn_predict_with_volume`.

**Comment by muschellij2** [comment]
I have added a switch for `flexconn_predict`.  The prediction is now volume-based by default.  This should be **much** lower in memory footprint.  Please confirm

**Comment by skeydan** [comment]
It now uses ~ 20 G (for me), which I can handle when running on cpu but not on (laptop) gpu...
But people will not be running this on laptops I guess...

**Comment by muschellij2** [comment]
Which part uses 20Gb?  The training or the prediction?  Training will take a lot I think as there are many batches and a large patch size.

The prediction shouldn't take that amount of memory to my knowledge.

**Comment by skeydan** [comment]
You're right - the high memory usage was a "baseline" after having loaded all the training data (because everything was in the same file).
I've now split the file into `flexconn_train.R` and `flexconn_test.R` to disentangle things.

Now if I do the prediction having loaded just one T1 and just one FLAIR, it's around 1.2G.
